insert into `languages`(`id`, `name`, `author`, `file_extension`)
values ('java', 'Java', 'James Gosling', 'java'),
        ('cpp', 'C++', 'Bjarne Stroustrup', 'cpp'),
        ('c', 'C', 'Dennis Ritchie', 'c'),
        ('csharp', 'C#', 'Microsoft', 'cs'),
        ('python', 'Python', 'Guido van Rossum', 'py'),
        ('php', 'PHP', 'Rasmus Lerdorf', 'php'),
        ('perl', 'Perl', 'Larry Wall', 'pl'),
        ('go', 'Go', 'Robert Griesemer', 'go'),
        ('scala', 'Scala', 'Martin Odersky', 'scala'),
        ('groovy', 'Groovy', 'James Strachan', 'groovy'),
        ('kotlin', 'Kotlin', 'JetBrains', 'kt'),
        ('swift', 'Swift', 'Apple', 'swift'),
        ('erlang', 'Erlang', 'Joe Armstrong', 'erl'),
        ('r', 'R', 'Ross Ihaka', 'r'),
        ('scilab', 'Scilab', 'INRIA', 'sci'),
        ('lua', 'Lua', 'Roberto Ierusalimschy', 'lua'),
        ('rust', 'Rust', 'Graydon Hoare', 'rs'),
        ('dart', 'Dart', 'Dart Team', 'dart'),
        ('coffeescript', 'CoffeeScript', 'Jeremy Ashkenas', 'coffee'),
        ('haskell', 'Haskell', 'Simon Peyton Jones', 'hs'),
        ('clojure', 'Clojure', 'Rich Hickey', 'clj'),
        ('ocaml', 'OCaml', 'Yann Hodique', 'ml');